src/Controllers/BlobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShangYi.Data;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Text;

namespace ShangYi.Controllers
{
	public class BlobController : Controller
	{
		private readonly ApplicationDbContext _context;

		public BlobController (ApplicationDbContext context)
		{
			_context = context;
		}

		public async Task<IActionResult> Index (int? id)
		{
			if (id == null)
				return NotFound ();

			var blob = await _context.BlobModel.SingleOrDefaultAsync (m => m.ID == id);
			if (blob == null)
				return NotFound ();

			var stream = new MemoryStream (blob.Content);
			Response.Headers.Add ("Content-Disposition",
				"attachment; filename=" + Uri.EscapeDataString (blob.FileName));
			return new FileStreamResult (stream, "application/octet-stream");
		}
	}
}

src/Controllers/mvc/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShangYi.Data;
using ShangYi.Models;
using Microsoft.AspNetCore.Http;

namespace ShangYi.Controllers.mvc
{
	public class CategoryController : Controller
	{
		private readonly ApplicationDbContext _context;

		public CategoryController (ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: Category
		public async Task<IActionResult> Index ()
		{
			return View (await _context.CategoryModel.ToListAsync ());
		}

		// GET: Category/Details/5
		public async Task<IActionResult> Details (int? id)
		{
			if (id == null)
			{
				return NotFound ();
			}

			var categoryModel = await _context.CategoryModel.SingleOrDefaultAsync(m => m.ID == id);
			if (categoryModel == null)
			{
				return NotFound ();
			}

			return View (categoryModel);
		}

		// GET: Category/Create
		public IActionResult Create ()
		{
			return View ();
		}

		// POST: Category/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create (CategoryModel categoryModel, IFormFile ThumbnailFile)
		{
			if (ModelState.IsValid && ThumbnailFile != null && ThumbnailFile.Length > 0)
			{
				categoryModel.Thumbnail =
					await BlobManager.SaveBlob (_context, ThumbnailFile);
				_context.Add (categoryModel);
				await _context.SaveChangesAsync ();

				return RedirectToAction ("Index");
			}

			foreach (var value in ModelState.Values)
				foreach (var error in value.Errors)
					ViewData["Error"] += error.ErrorMessage + ";";

			if (ThumbnailFile == null || ThumbnailFile.Length == 0)
				ViewData["Error"] += "No Thumbnail;";
			return View (categoryModel);
		}

		// GET: Category/Edit/5
		public async Task<IActionResult> Edit (int? id)
		{
			if (id == null)
			{
				return NotFound ();
			}

			var categoryModel = await _context.CategoryModel.SingleOrDefaultAsync(m => m.ID == id);
			if (categoryModel == null)
			{
				return NotFound ();
			}
			return View (categoryModel);
		}

		// POST: Category/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit (int id, CategoryModel categoryModel, IFormFile ThumbnailFile)
		{
			if (id != categoryModel.ID)
			{
				return NotFound ();
			}

			if (ModelState.IsValid)
			{
				try
				{
					var categoryModel_old = await _context.CategoryModel.AsNoTracking ()
						.SingleOrDefaultAsync(m => m.ID == id);

					if (ThumbnailFile != null && ThumbnailFile.Length > 0)
					{
						await BlobManager.DeleteBlob (_context, categoryModel_old.Thumbnail);
						categoryModel.Thumbnail =
							await BlobManager.SaveBlob (_context, ThumbnailFile);
					}
					else
					{
						categoryModel.Thumbnail = categoryModel_old.Thumbnail;
					}
					_context.Update (categoryModel);
					await _context.SaveChangesAsync ();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!CategoryModelExists (categoryModel.ID))
					{
						return NotFound ();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction ("Index");
			}
			return View (categoryModel);
		}

		// GET: Category/Delete/5
		public async Task<IActionResult> Delete (int? id)
		{
			if (id == null)
			{
				return NotFound ();
			}

			var categoryModel = await _context.CategoryModel.SingleOrDefaultAsync(m => m.ID == id);
			if (categoryModel == null)
			{
				return NotFound ();
			}

			return View (categoryModel);
		}

		// POST: Category/Delete/5
		[HttpPost, ActionName ("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed (int id)
		{
			var categoryModel = await _context.CategoryModel.SingleOrDefaultAsync(m => m.ID == id);
			await BlobManager.DeleteBlob (_context, categoryModel.Thumbnail);
			_context.CategoryModel.Remove (categoryModel);
			await _context.SaveChangesAsync ();
			return RedirectToAction ("Index");
		}

		private bool CategoryModelExists (int id)
		{
			return _context.CategoryModel.Any (e => e.ID == id);
		}
	}
}

src/Views/Category/Create.cshtml
@model ShangYi.Models.CategoryModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>CategoryModel</h4>
        <hr />
        <div class="text-danger">@ViewData["Error"]</div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="CID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CID" class="form-control" />
                <span asp-validation-for="CID" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ParentID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ParentID" class="form-control" />
                <span asp-validation-for="ParentID" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Thumbnail" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input name="ThumbnailFile" type="file" />
                <span asp-validation-for="Thumbnail" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="isLeaf" />
                    <label asp-for="isLeaf"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Views/Category/Delete.cshtml
@model ShangYi.Models.CategoryModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CategoryModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ParentID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ParentID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Thumbnail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.isLeaf)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.isLeaf)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/Views/Category/Details.cshtml
@model ShangYi.Models.CategoryModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>CategoryModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ParentID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ParentID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Thumbnail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.isLeaf)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.isLeaf)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/Views/Category/Edit.cshtml
@model ShangYi.Models.CategoryModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>CategoryModel</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="CID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CID" class="form-control" />
                <span asp-validation-for="CID" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ParentID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ParentID" class="form-control" />
                <span asp-validation-for="ParentID" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Thumbnail" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input name="ThumbnailFile" type="file" />
                <span asp-validation-for="Thumbnail" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="isLeaf" />
                    <label asp-for="isLeaf"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Views/Category/Index.cshtml
@model IEnumerable<ShangYi.Models.CategoryModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ParentID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Thumbnail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isLeaf)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.OrderBy (m => m.CID).OrderBy (m => m.ParentID)) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParentID)
            </td>
            <td>
                <a asp-controller="Blob" asp-action="Index" asp-route-id="@item.Thumbnail">Download</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isLeaf)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>